# Generated by Django 5.2.8 on 2025-12-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_description_alter_course_title_and_more"),
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("user", "paid_course"), ("user", "paid_lesson")},
        ),
    ]
