# Generated by Django 5.2.8 on 2026-01-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_date_alter_payment_paid_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activation_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="token_expires_at",
        ),
    ]
