# Generated by Django 5.2.8 on 2026-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payment_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
