# Generated by Django 5.2.8 on 2026-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
