# Generated by Django 5.2.8 on 2026-01-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="ext_pay_sess_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
