# Generated by Django 5.2.8 on 2025-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
