# Generated by Django 5.2.8 on 2026-01-07 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_lesson_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Сумма оплаты"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Сумма оплаты"),
        ),
    ]
