# Generated by Django 6.0.1 on 2026-01-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_subscription_course_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
    ]
