# Generated by Django 6.0.1 on 2026-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
